#include<stdio.h>
#include<math.h>
#include<conio.h>
#include<iostream.h>
#include<iomanip.h>
void main()
{
 int basic=12000,allowance=2000,total;
 total=basic+allowance;
 clrscr();
 cout<<setw(10)<<"basic"<<setw(10)<<basic<<endl;
 cout<<setw(10)<<"allowance"<<setw(10)<<allowance<<endl;
 cout<<"____________________"<<endl;
 cout<<setw(10)<<"total"<<setw(10)<<total;

 cout<<endl<<setfill('s')<<setw(10)<<"fff";
 cout<<endl<<setprecision(0)<<sqrt(10);

 getch();
}
