#include<stdio.h>
#include"conio.h"
#define pi 3.14
#define pyy 3.14159265
#define mssg "\n\nprograme for #define\n"
#define being void main(){
#define print printf("\nnow i understand the use of #define completely.");
#define loop for(i=1;i<=10;i++)
#define data_type int
#define end getch();}
being /*actually it is void main(){*/
data_type i; /*data_type=int*/
float py,pye=pyy;/*here it means pye=3.14159265*/
clrscr();
printf(mssg);/*mssg=\n\nprograme for #define*/
py=pi; /* it means py=3.14*/
printf("\n\nthe value of pi is =%.2f\n",py);/*pi = 3.14*/
printf("\nthe full value of pi is =%f\n\n",pye);

loop/*loop=for(i=0;i<=10;i++)*/
{
printf("%d\t",i);
}
print/*print=printf("i understand the use of #define");*/
end/*here end means getch();}*/




