		   /*prog. for print values*/
#include<stdio.h>
#include<conio.h>
void main()
	{                                    /*body stars*/
	int a,b;
      //	a=3;
      //	b=8;
	clrscr();                             /*decleration of variables*/
	printf("\n\t enter two no.\n");
      scanf("\n\t%d""%d",&a,&b);
	printf("\n\t the values of a & b are a=%d" " b=%d" , a,b);
	getch();
	}				    /*end of body*/
