<%@ Page Title="" Language="C#" MasterPageFile="~/General Module/GeneralMasterPage.master" AutoEventWireup="true" CodeFile="Departments.aspx.cs" Inherits="General_Module_Departments" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table style="width: 100%">
    <tr>
        <td style="width: 163px; height: 29px"></td>
        <td style="width: 836px; height: 29px"></td>
        <td style="height: 29px"></td>
    </tr>
    <tr>
        <td style="width: 163px; height: 1094px"></td>
        <td style="width: 836px; height: 1094px">
            <h3 class="body-el-subtitle standard-body-el-subtitle article-sub-title anim-in-view in-view" style="box-sizing: inherit; font-weight: normal; margin: 0px 0px 1rem 47.5938px; font-family: Museo-300, Helvetica, Arial, sans-serif; font-size: 1.375rem; line-height: 38px; color: rgb(44, 60, 64); display: block; letter-spacing: 0.025em; -webkit-font-smoothing: antialiased; width: 739.188px; float: none; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong>Ear nose and throat (ENT)</strong></h3>
            <p class="body-el-text standard-body-el-text" style="box-sizing: inherit; font-family: MuseoSans-300, Helvetica, Arial, sans-serif; font-size: 17px; line-height: 1.2; color: rgb(99, 101, 106); letter-spacing: 0.85px; margin-left: 47.5938px; margin-right: 0px; margin-bottom: 1rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                The ENT department provides care for patients with a variety of problems, including:</p>
            <ul class="body-el-ul standard-body-el-ul" style="box-sizing: inherit; list-style-position: inside; list-style-type: disc; margin-left: 47.5938px; margin-right: 0px; margin-bottom: 1rem; color: rgb(99, 101, 106); font-family: MuseoSans-300, Helvetica, Arial, sans-serif; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: 0.85px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <li style="box-sizing: inherit;">general ear, nose and throat diseases</li>
                <li style="box-sizing: inherit;">neck lumps</li>
                <li style="box-sizing: inherit;">cancers of the head and neck area</li>
                <li style="box-sizing: inherit;">tear duct problems</li>
                <li style="box-sizing: inherit;">facial skin lesions</li>
                <li style="box-sizing: inherit;">balance and hearing disorders</li>
                <li style="box-sizing: inherit;">snoring and sleep apnoea</li>
                <li style="box-sizing: inherit;">ENT allergy problems</li>
                <li style="box-sizing: inherit;">salivary gland diseases</li>
                <li style="box-sizing: inherit;">voice disorders.</li>
            </ul>
            <p>
                &nbsp;</p>
            <h3 class="body-el-subtitle standard-body-el-subtitle article-sub-title anim-in-view in-view" style="box-sizing: inherit; font-weight: normal; margin: 0px 0px 1rem 47.5938px; font-family: Museo-300, Helvetica, Arial, sans-serif; font-size: 1.375rem; line-height: 38px; color: rgb(44, 60, 64); display: block; letter-spacing: 0.025em; -webkit-font-smoothing: antialiased; width: 739.188px; float: none; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong>General surgery</strong></h3>
            <p class="body-el-text standard-body-el-text" style="box-sizing: inherit; font-family: MuseoSans-300, Helvetica, Arial, sans-serif; font-size: 17px; line-height: 1.2; color: rgb(99, 101, 106); letter-spacing: 0.85px; margin-left: 47.5938px; margin-right: 0px; margin-bottom: 1rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                The general surgery ward covers a wide range of surgery and includes:</p>
            <ul class="body-el-ul standard-body-el-ul" style="box-sizing: inherit; list-style-position: inside; list-style-type: disc; margin-left: 47.5938px; margin-right: 0px; margin-bottom: 1rem; color: rgb(99, 101, 106); font-family: MuseoSans-300, Helvetica, Arial, sans-serif; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: 0.85px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <li style="box-sizing: inherit;">day surgery</li>
                <li style="box-sizing: inherit;">thyroid surgery</li>
                <li style="box-sizing: inherit;">kidney transplants</li>
                <li style="box-sizing: inherit;">colon surgery</li>
                <li style="box-sizing: inherit;">laparoscopic cholecystectomy (gallbladder removal)</li>
                <li style="box-sizing: inherit;">endoscopy</li>
                <li style="box-sizing: inherit;">breast surgery.</li>
            </ul>
            <p class="body-el-text standard-body-el-text" style="box-sizing: inherit; font-family: MuseoSans-300, Helvetica, Arial, sans-serif; font-size: 17px; line-height: 1.2; color: rgb(99, 101, 106); letter-spacing: 0.85px; margin-left: 47.5938px; margin-right: 0px; margin-bottom: 1rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                Day surgery units have a high turnover of patients who attend for minor surgical procedures such as hernia repairs.</p>
            <h3 class="body-el-subtitle standard-body-el-subtitle article-sub-title anim-in-view in-view" style="box-sizing: inherit; font-weight: normal; margin: 0px 0px 1rem 47.5938px; font-family: Museo-300, Helvetica, Arial, sans-serif; font-size: 1.375rem; line-height: 38px; color: rgb(44, 60, 64); display: block; letter-spacing: 0.025em; -webkit-font-smoothing: antialiased; width: 739.188px; float: none; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong>Gynaecology</strong></h3>
            <p class="body-el-text standard-body-el-text" style="box-sizing: inherit; font-family: MuseoSans-300, Helvetica, Arial, sans-serif; font-size: 17px; line-height: 1.2; color: rgb(99, 101, 106); letter-spacing: 0.85px; margin-left: 47.5938px; margin-right: 0px; margin-bottom: 1rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                These departments investigate and treat problems of the female urinary tract and reproductive organs, such as endometritis,<span class="Apple-converted-space">&nbsp;</span><a class="body-el-link standard-body-el-link" href="http://www.netdoctor.co.uk/health_advice/facts/assistedconception.htm" hrefid="000361" style="box-sizing: inherit; background: transparent; color: rgb(246, 75, 119); text-decoration: none; transition: color 0.3s ease-in-out;" target="_parent">infertility</a><span class="Apple-converted-space">&nbsp;</span>and<span class="Apple-converted-space">&nbsp;</span><a class="body-el-link standard-body-el-link" href="http://www.netdoctor.co.uk/womenshealth/sui/ui_005139.htm" hrefid="005139" style="box-sizing: inherit; background: transparent; color: rgb(246, 75, 119); text-decoration: none; transition: color 0.3s ease-in-out;" target="_parent">incontinence</a>.</p>
            <p class="body-el-text standard-body-el-text" style="box-sizing: inherit; font-family: MuseoSans-300, Helvetica, Arial, sans-serif; font-size: 17px; line-height: 1.2; color: rgb(99, 101, 106); letter-spacing: 0.85px; margin-left: 47.5938px; margin-right: 0px; margin-bottom: 1rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                They also provide a range of care for cervical smear screening and post-menopausal bleeding checks.</p>
            <p class="body-el-text standard-body-el-text" style="box-sizing: inherit; font-family: MuseoSans-300, Helvetica, Arial, sans-serif; font-size: 17px; line-height: 1.2; color: rgb(99, 101, 106); letter-spacing: 0.85px; margin-left: 47.5938px; margin-right: 0px; margin-bottom: 1rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                They usually have:</p>
            <ul class="body-el-ul standard-body-el-ul" style="box-sizing: inherit; list-style-position: inside; list-style-type: disc; margin-left: 47.5938px; margin-right: 0px; margin-bottom: 1rem; color: rgb(99, 101, 106); font-family: MuseoSans-300, Helvetica, Arial, sans-serif; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: 0.85px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                <li style="box-sizing: inherit;">a specialist ward</li>
                <li style="box-sizing: inherit;">day surgery unit</li>
                <li style="box-sizing: inherit;">emergency gynaecology assessment unit</li>
                <li style="box-sizing: inherit;">outpatient clinics.</li>
            </ul>
            <h3 class="body-el-subtitle standard-body-el-subtitle article-sub-title anim-in-view in-view" style="box-sizing: inherit; font-weight: normal; margin: 0px 0px 1rem 47.5938px; font-family: Museo-300, Helvetica, Arial, sans-serif; font-size: 1.375rem; line-height: 38px; color: rgb(44, 60, 64); display: block; letter-spacing: 0.025em; -webkit-font-smoothing: antialiased; width: 739.188px; float: none; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong>Haematology</strong></h3>
            <p class="body-el-text standard-body-el-text" style="box-sizing: inherit; font-family: MuseoSans-300, Helvetica, Arial, sans-serif; font-size: 17px; line-height: 1.2; color: rgb(99, 101, 106); letter-spacing: 0.85px; margin-left: 47.5938px; margin-right: 0px; margin-bottom: 1rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                Haematology services work closely with the hospital laboratory. These doctors treat blood diseases and malignancies linked to the blood, with both new referrals and emergency admissions being seen.</p>
            <h3 class="body-el-subtitle standard-body-el-subtitle article-sub-title anim-in-view in-view" style="box-sizing: inherit; font-weight: normal; margin: 0px 0px 1rem 47.5938px; font-family: Museo-300, Helvetica, Arial, sans-serif; font-size: 1.375rem; line-height: 38px; color: rgb(44, 60, 64); display: block; letter-spacing: 0.025em; -webkit-font-smoothing: antialiased; width: 739.188px; float: none; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong>Nephrology</strong></h3>
            <p class="body-el-text standard-body-el-text" style="box-sizing: inherit; font-family: MuseoSans-300, Helvetica, Arial, sans-serif; font-size: 17px; line-height: 1.2; color: rgb(99, 101, 106); letter-spacing: 0.85px; margin-left: 47.5938px; margin-right: 0px; margin-bottom: 1rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                This department monitors and assesses patients with kidney (renal) problems.</p>
            <p class="body-el-text standard-body-el-text" style="box-sizing: inherit; font-family: MuseoSans-300, Helvetica, Arial, sans-serif; font-size: 17px; line-height: 1.2; color: rgb(99, 101, 106); letter-spacing: 0.85px; margin-left: 47.5938px; margin-right: 0px; margin-bottom: 1rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                Nephrologists (kidney specialists) will liaise with the transplant team in cases of kidney transplants.</p>
            <p class="body-el-text standard-body-el-text" style="box-sizing: inherit; font-family: MuseoSans-300, Helvetica, Arial, sans-serif; font-size: 17px; line-height: 1.2; color: rgb(99, 101, 106); letter-spacing: 0.85px; margin-left: 47.5938px; margin-right: 0px; margin-bottom: 1rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                They also supervise the dialysis day unit for people who are waiting for a kidney transplant or who are unable to have a transplant for any reason.</p>
            <h3 class="body-el-subtitle standard-body-el-subtitle article-sub-title anim-in-view in-view" style="box-sizing: inherit; font-weight: normal; margin: 0px 0px 1rem 47.5938px; font-family: Museo-300, Helvetica, Arial, sans-serif; font-size: 1.375rem; line-height: 38px; color: rgb(44, 60, 64); display: block; letter-spacing: 0.025em; -webkit-font-smoothing: antialiased; width: 739.188px; float: none; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><strong>Neurology</strong></h3>
            <p class="body-el-text standard-body-el-text" style="box-sizing: inherit; font-family: MuseoSans-300, Helvetica, Arial, sans-serif; font-size: 17px; line-height: 1.2; color: rgb(99, 101, 106); letter-spacing: 0.85px; margin-left: 47.5938px; margin-right: 0px; margin-bottom: 1rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                This unit deals with disorders of the nervous system, including the brain and spinal cord. It&#39;s run by doctors who specialise in this area (neurologists) and their staff.</p>
            <p class="body-el-text standard-body-el-text" style="box-sizing: inherit; font-family: MuseoSans-300, Helvetica, Arial, sans-serif; font-size: 17px; line-height: 1.2; color: rgb(99, 101, 106); letter-spacing: 0.85px; margin-left: 47.5938px; margin-right: 0px; margin-bottom: 1rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                There are also paediatric neurologists who treat children. Neurologists may also be involved in clinical research and clinical trials.</p>
            <p class="body-el-text standard-body-el-text" style="box-sizing: inherit; font-family: MuseoSans-300, Helvetica, Arial, sans-serif; font-size: 17px; line-height: 1.2; color: rgb(99, 101, 106); letter-spacing: 0.85px; margin-left: 47.5938px; margin-right: 0px; margin-bottom: 1rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                Specialist nurses (epilepsy, multiple sclerosis) liaise with patients, consultants and GPs to help with any problems that may occur between outpatient appointments.</p>
            <p class="body-el-text standard-body-el-text" style="box-sizing: inherit; font-family: MuseoSans-300, Helvetica, Arial, sans-serif; font-size: 17px; line-height: 1.2; color: rgb(99, 101, 106); letter-spacing: 0.85px; margin-left: 47.5938px; margin-right: 0px; margin-bottom: 1rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
                &nbsp;</p>
        </td>
        <td style="height: 1094px"></td>
    </tr>
</table>
</asp:Content>

